In [1]:
imimport numpy as np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [4]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [5]:
print(y)

[ 5 20 14 32 22 38]


In [6]:
model = LinearRegression()

In [7]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
y_pred = model.intercept_ + model.coef_ * x

In [11]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [13]:
x_new = np.arange(5).reshape((-1, 1))
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [14]:
y_new = model.predict(x_new)

In [15]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
